---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-app
  labels:
    app: tic-tac-toe-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe-app
  template:
    metadata:
      labels:
        app: tic-tac-toe-app
    spec:
      containers:
      - name: tic-tac-toe-container
        image: 021072884677.dkr.ecr.us-east-1.amazonaws.com/tic-tac-toe:3
        ports:
        - containerPort: 5173
...
